# Generated by Django 3.0.4 on 2020-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_agents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
