# Generated by Django 3.0.4 on 2020-03-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_saved_agents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.TextField(blank=True),
        ),
    ]
