# Generated by Django 3.0.4 on 2020-03-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200312_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_token',
        ),
    ]
