# Generated by Django 3.0.4 on 2020-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='submission_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
