# Generated by Django 3.0.4 on 2020-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0002_agent_submission_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
