# Generated by Django 3.0.4 on 2020-03-12 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sets', '0003_auto_20200311_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='sets.Agency'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='genres_of_interest',
            field=models.TextField(blank=True),
        ),
    ]
